
package mainpackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloDarknessMyOldFriendService", 
        targetNamespace = "http://mainpackage/", 
        wsdlLocation = "http://localhost:9999/ws3/hellodarkness?wsdl")
@HandlerChain(file="handler-chain.xml")
public class HelloDarknessMyOldFriendService
    extends Service
{

    private final static URL HELLODARKNESSMYOLDFRIENDSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLODARKNESSMYOLDFRIENDSERVICE_EXCEPTION;
    private final static QName HELLODARKNESSMYOLDFRIENDSERVICE_QNAME = new QName("http://mainpackage/", "HelloDarknessMyOldFriendService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws3/hellodarkness?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLODARKNESSMYOLDFRIENDSERVICE_WSDL_LOCATION = url;
        HELLODARKNESSMYOLDFRIENDSERVICE_EXCEPTION = e;
    }

    public HelloDarknessMyOldFriendService() {
        super(__getWsdlLocation(), HELLODARKNESSMYOLDFRIENDSERVICE_QNAME);
    }

    public HelloDarknessMyOldFriendService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLODARKNESSMYOLDFRIENDSERVICE_QNAME, features);
    }

    public HelloDarknessMyOldFriendService(URL wsdlLocation) {
        super(wsdlLocation, HELLODARKNESSMYOLDFRIENDSERVICE_QNAME);
    }

    public HelloDarknessMyOldFriendService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLODARKNESSMYOLDFRIENDSERVICE_QNAME, features);
    }

    public HelloDarknessMyOldFriendService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloDarknessMyOldFriendService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IHelloDarknessMyOldFriend
     */
    @WebEndpoint(name = "HelloDarknessMyOldFriendPort")
    public IHelloDarknessMyOldFriend getHelloDarknessMyOldFriendPort() {
        return super.getPort(new QName("http://mainpackage/", "HelloDarknessMyOldFriendPort"), IHelloDarknessMyOldFriend.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloDarknessMyOldFriend
     */
    @WebEndpoint(name = "HelloDarknessMyOldFriendPort")
    public IHelloDarknessMyOldFriend getHelloDarknessMyOldFriendPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mainpackage/", "HelloDarknessMyOldFriendPort"), IHelloDarknessMyOldFriend.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLODARKNESSMYOLDFRIENDSERVICE_EXCEPTION!= null) {
            throw HELLODARKNESSMYOLDFRIENDSERVICE_EXCEPTION;
        }
        return HELLODARKNESSMYOLDFRIENDSERVICE_WSDL_LOCATION;
    }

}
